### ISSUE TITLE
Understanding the plugin

### ISSUE THREAD

**Issue by user454322** [reinbach/sd-postgresql#1]
First of all, thanks for this plugin.

More than an isue these are questions to understand how the plugin works:

I see this plugin gives info about current and max connections.
Are these parameters based on roles, i.e., `pg_roles.rolconnlimit` 
or 
server based ,i.e., `postgresql.conf:max_connections`?

Are the connection being monitored only for the database specified in `config.cfg` or for all the databases in the server?

Cheers!

**Comment by reinbach** [comment]
Hi @user454322 

The max connections information comes from the pg_settings table which relates to postgresql.conf file. So not role based.
"SELECT setting AS mc FROM pg_settings WHERE name = 'max_connections'"

The current connections information comes from the pg_database table and counts all the connections via pg_stat_activity. So that should be server wide, not by role.
"SELECT COUNT(datid) FROM pg_database AS d LEFT JOIN pg_stat_activity AS s ON (s.datid = d.oid)"

Hope that helps, it's been a while since I worked on this.

**Comment by user454322** [comment]
Cool!

Yep, it makes more sense to monitor the number of coennctions of a server
